### ISSUE TITLE
应该是 “闷声大发财”

### ISSUE THREAD

**Issue by namoen0301** [dkwingsmt/haha#4]
![qq 20160409201745](https://cloud.githubusercontent.com/assets/4280572/14403579/23569df4-fe90-11e5-8603-27ccfa32ad1b.png)

**Comment by namoen0301** [comment]
提交了个 Pull Request 这个关掉吧

**Comment by ghost** [comment]
其实这个是有争议的。

> 新闻二台与翡翠台针对此段发言所配字幕稍有不同。例如，对于原话「闷声大发财」，新闻二台用的是「发大财」，而翡翠台用的是「大发财」；除此之外，很多口语细节都没有在字幕中反映出来。鉴于此，本段语录尽量根据江的原话进行编写。视频详见[有线新闻台版本](https://www.youtube.com/watch?v=CEvYpWnzC0k)和[翡翠台版本](https://www.youtube.com/watch?v=lBOwxXxesBo)。

参考[江泽民 - 维基语录，自由的名人名言录](https://zh.wikiquote.org/zh/%E6%B1%9F%E6%B3%BD%E6%B0%91#.E6.80.92.E6.96.A5.E9.A6.99.E6.B8.AF.E8.AE.B0.E8.80.85)

**Comment by hczhcz** [comment]
这个原视频可以听得出啊

**Comment by paperbag** [comment]
我试图去听，感觉很难分辨。谷歌搜索这两个表达都有相当数量的结果。
"闷声发大财" About 771,000 results
"闷声大发财" About 79,800 results

然而我也不想纠结这个啦，只要能开心的膜就可以了。
